packages:
  - artifacts/*
  - lib/*
  - lib/integrations/*
  - scripts

autoInstallPeers: false

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver

overrides:
  '@esbuild-kit/esm-loader': npm:tsx@^4.21.0

