kind = "web"
previewPath = "/"
title = "Salon Booking App"
version = "1.0.0"
id = "artifacts/salon-booking"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 20859
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/salon-booking run dev"

[services.env]
PORT = "20859"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/salon-booking", "run", "build"]
publicDir = "artifacts/salon-booking/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
